### ISSUE TITLE
There is bug in software

### ISSUE THREAD

**Issue by jamesa-unito** [jodigiordano/gg#76]
![image](https://github.com/user-attachments/assets/7eb2af2e-3116-4fe6-9235-6a34f5a47cbf)

Fails to load in Chrome but loads in Firefox

:(

**Comment by jodigiordano** [comment]
Yo @jamesa-unito! Thank you for the bug report :)

I can reproduce the issue by setting an invalid JSON in the editor (view > json editor).
Fixed in https://github.com/jodigiordano/gg/pull/77 and deployed in production.

That said, I don't understand why you have an invalid JSON to start with :thinking:

**Comment by jodigiordano** [comment]
I'm closing this. The issue was an invalid JSON string in the local storage. This should be fixed in #66
